- .github/workflows/pr-open.yml
- src/main.ts
SonarCloud hasn't been moved until this PR.  It required an issue via Platform Team.  I accidentally threw up a block by keeping greenfield-pipeline in the bcgov-nr organization.
https://github.com/BCDevOps/devops-requests/issues/1373
> Complete move of org (bcgov-nr -> bcgov) with SonarCloud

- .github/workflows/main.yml
Adding Java projects under .apis/ threw off SonarCloud.  This points the scans just to ./src, which is the default TS/JS app.
> Point main merge sonarcloud to only ./src

- backend/package-lock.json
- backend/package.json
Copied from previous, which happened before the backend was added.
---
Updated to 1.2.6
One outstanding:
```
├─┬ @nestjs/cli@8.2.4
│ ├─┬ @angular-devkit/schematics-cli@13.3.0
│ │ └── minimist@1.2.5 
```
Dependabot:
```
Minimist <=1.2.5 is vulnerable to Prototype Pollution via file index.js, function setKey() (lines 69-95).
```
https://github.com/bcgov/greenfield-template/security/dependabot/5
> deps/minimist (backend)

- .github/workflows/pr-open.yml
Image and repo scanner.  Has previously been a pain, but should be revisited.
> Reenable Trivy, point at frontend and backend

- .github/openshift/deploy.frontend.yml
Make PROMOTE parameter for frontend deployment required.  Previously had a useless default.
> Frontend deploy PROMOTE = required

- .github/workflows/merge-main.yml
- .github/workflows/pr-close.yml
- backend/src/app.controller.spec.ts
- backend/src/app.service.ts
- backend/src/main.ts
- backend/test/app.e2e-spec.ts
- frontend/src/app.controller.spec.ts
- frontend/src/app.service.ts
- frontend/src/main.ts
- frontend/test/app.e2e-spec.ts
Stale images have been causing us to delete all images, creating much slower and less reliable rolling upgrades.  The issue appears to be between OpenShift and GHCR.io.
> Improve image handling and promotion

- .github/workflows/merge-main.yml
- .github/workflows/pr-close.yml
- frontend/src/app.controller.spec.ts
- frontend/src/app.service.ts
- frontend/test/app.e2e-spec.ts
There are multiple jobs using `environment.name: PROD`, which kicks up multiple review/deploy prompts.  Shuffle the logic to use only one prompt.
> Reenable PROD deployment gate, prompt only once

- .github/workflows/merge-main.yml
- .github/workflows/pr-open.yml
Allow Merge to Main workflow to be run manually.  Plus cleanup (reordering, commenting out GitHub context dump).
Benefit: Kick off TEST/PROD deployments manually.  For fails, GH Actions outages (which happens!) or un-triggered changes.
> workflow_dispatch for merge-main; comment out context

- .github/workflows/merge-main.yml
- .github/workflows/pr-open.yml
PRs had been either building images or reusing ones from PROD.  Some teams are not going to PROD frequently, so it makes sense to use TEST images instead.
(There was also some redundant image promotion code that's been removed.)
> PRs fall back to TEST images, not PROD

- .github/workflows/pr-open.yml
Add to PR description at submission instead of comments on every run.  This should mean we see significantly fewer comments and GitHub notification emails.
Without using the build completion comment as the end we need a different final step.  SonarCloud should work, so prereqs have been revised.
<p>
---
[Backend](https://nr-quickstart-helpers-537-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-helpers-537-frontend.apps.silver.devops.gov.bc.ca/) available
> Use PR description add, remove comment, revise prereqs

- .github/workflows/pr-open.yml
- frontend/openshift.deploy.yml
Simplify the pipeline while undergoing heavy revision.
Extend Frontend's readiness probe, since it's been semi-regularly failing verification.
<p>
---
[Backend](https://nr-quickstart-helpers-539-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-helpers-539-frontend.apps.silver.devops.gov.bc.ca/) available
> Simplify prereqs/deploys, extend frontend readiness probe

- frontend/openshift.deploy.yml
Earlier change to probe wasn't useful.  Deployment Verification (_deploy helper) was frequently false failing.  Retries have been added in the Helpers repo, so this PR is testing that and undoing the previous probe change.
<p>
---
[Backend](https://nr-quickstart-helpers-540-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-helpers-540-frontend.apps.silver.devops.gov.bc.ca/) available
> Testing and restore frontend liveness probe periodseconds=15

- .github/workflows/pr-open.yml
No longer need to add `<p>` to get a space.
---
[Backend](https://nr-quickstart-helpers-553-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-helpers-553-frontend.apps.silver.devops.gov.bc.ca/) available
> Bump to DerekRoberts/action-pr-description-add@v0.0.2

- .github/workflows/pr-open.yml
PRs kicked off by forks are failing on package creation. This is very likely permission related.
---
[Backend](https://nr-quickstart-helpers-555-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-helpers-555-frontend.apps.silver.devops.gov.bc.ca/) available
> Set token permissions for builds, failing for fork PRs

- .github/workflows/pr-open.yml
SonarCloud comments are still adding up.  Using SC as a final step also wasn't working for merge requirements.  This PR makes only unit tests a prerequisite for SonarCloud and stops PR commenting.  Merge requirements are changed to require a successful reporting of SC, not of the kick-off job itself.
Changes were made to branch protection that do not show in this pull request.  The settings are available here:
`Settings > Branches > main: edit > Require status checks to pass before merging.`
SonarCloud will continue to fail the pipeline if a problem is found.
> Stop SonarCloud comments, but still stop workflow on fail

- .github/workflows/merge-main.yml
- .github/workflows/pr-open.yml
Try setting up SonarCloud in monorepo mode.  Uses two projects set up as monorepos.
---
[Backend](https://nr-quickstart-typescript-580-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-580-frontend.apps.silver.devops.gov.bc.ca/) available
> SonarCloud monorepo mode (2x projects)

- .github/workflows/pr-open.yml
Run SonarCloud in _unit-tests helper.  Tested using a temporary feature branch.  It can't be merged until that option is released in nr-quickstart-helpers@v0.0.3.
Update: Temporarily using main instead of a version number to merge.  Will fix.
---
[Backend](https://nr-quickstart-typescript-582-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-582-frontend.apps.silver.devops.gov.bc.ca/) available
---
Any successful deployments (not always required) will be …
> SonarCloud in _unit-tests helper

- .github/workflows/merge-main.yml
- .github/workflows/pr-open.yml
---
[Backend](https://nr-quickstart-typescript-624-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-624-frontend.apps.silver.devops.gov.bc.ca/) available
> Update bcgov-nr/action-deployer-openshift to v0.0.2

- .github/workflows/unit-tests.yml
Skip unit tests and associated noise/costs until a PR is taken out of draft.
---
[Backend](https://nr-quickstart-typescript-633-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-633-frontend.apps.silver.devops.gov.bc.ca/) available
> Skip Unit Tests when PR=draft

- .github/workflows/merge-main.yml
- .github/workflows/unit-tests.yml
Trivy kicking up errors in merge-main.yml has been a problem.  This makes sure it runs on PRs with the remaining merge portion for reporting and comparison.
---
[Backend](https://nr-quickstart-typescript-667-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-667-frontend.apps.silver.devops.gov.bc.ca/) available
> Moved Trivy from merge to test/analyse workflow

- .github/workflows/merge-main.yml
GitHub Actions can now run CodeQL without needing a custom job in our workflows.
---
[Backend](https://nr-quickstart-typescript-799-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-799-frontend.apps.silver.devops.gov.bc.ca/) available
> Switch to auto/default CodeQL runs

- .github/workflows/merge-main.yml
Reverts bcgov/nr-quickstart-typescript#799
Switching to auto CodeQL runs only works for a limited number of languages, not covering Java, and requires extra config after consuming this template.  Maybe it'll be more automatic in future, but for now let's stick with the extra workflow job.
---
[Backend](https://nr-quickstart-typescript-805-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-805-frontend.apps.silver.devops.gov.bc.ca/) available
> Revert "Switch to auto/default CodeQL runs"

- .github/dependabot.yml
Renovate is in place and more or less running even with Dependabot.  Comment out npm packages from .github/dependabot.yml, leaving Dependabot only running GitHub Actions updates.
---
[Backend](https://nr-quickstart-typescript-878-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-878-frontend.apps.silver.devops.gov.bc.ca/) available
> Use Renovate instead of Dependabot for npm udpates

- .github/workflows/pr-open.yml
- .github/workflows/renovate.yml
- renovate.json
Renovate is creating many dependency dashboard issues and other noise.  This attempts to combine PRs and stop the issues.
Update: Renovate is getting moved out of this repo soon.
> Simplify, disable dependency dashboard

- .github/workflows/merge-main.yml
- .github/workflows/pr-close.yml
Addresses a bug that came up after moving one of the templated repos between orgs.
---
[Backend](https://nr-quickstart-typescript-1020-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-1020-frontend.apps.silver.devops.gov.bc.ca/) available
> Set permissions.package:write for retag action

- .github/workflows/pr-close.yml
- .github/workflows/pr-open.yml
this will allow multiple workflows to run in parallel without conflicting.
previously you could clash two different workflows, like close in case they ran at the same time
---
[Backend](https://nr-quickstart-typescript-1042-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-1042-frontend.apps.silver.devops.gov.bc.ca/) available
> ci: updating concurrency on pr open and close

- .github/workflows/merge-main.yml
Deployer action version bump missed for main merge.
---
[Backend](https://quickstart-openshift-1104-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1104-frontend.apps.silver.devops.gov.bc.ca/) available
> Bump deployer action version

- .github/workflows/pr-open.yml
The fallback tag checker in the builder action is now building every time instead of being smart enough to reuse fallback tags.  Test and merge fixed version of builder.
---
[Backend](https://quickstart-openshift-1125-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1125-frontend.apps.silver.devops.gov.bc.ca/) available
> Restore smart builder from action

- .github/workflows/unit-tests.yml
Use node 20 for tests.  Previously on 16, which had been causing test failures.  (inconsistently?!?)
---
[Backend](https://quickstart-openshift-1126-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1126-frontend.apps.silver.devops.gov.bc.ca/) available
---
[Backend](https://quickstart-openshift-1126-backend.apps.silver.devops.gov.bc.ca/) available …
> Use node 20 for unit tests

- .github/workflows/pr-open.yml
Only run PR description add when a PR has been opened/reopened.  Save resources, reduce noise.
---
[Backend](https://quickstart-openshift-1139-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1139-frontend.apps.silver.devops.gov.bc.ca/) available
> Run PR description add if PR opened or reopened

- .github/workflows/pr-open.yml
Database didn't have any deployment triggers, so it was always deploying in PRs.
---
[Backend](https://quickstart-openshift-1236-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1236-frontend.apps.silver.devops.gov.bc.ca/) available
> PR deployment triggers for db

- frontend/Caddyfile
- frontend/Dockerfile
- frontend/openshift.deploy.yml
Update Caddy to 2.6.4, which requires an OpenShift context.
---
[Backend](https://quickstart-openshift-1238-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1238-frontend.apps.silver.devops.gov.bc.ca/) available
> Caddy update and OpenShift security context

- frontend/.dockerignore
- frontend/Caddyfile
- frontend/openshift.deploy.yml
---
[Backend](https://quickstart-openshift-1240-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1240-frontend.apps.silver.devops.gov.bc.ca/) available
> Set Log Level for Caddy

- .github/workflows/unit-tests.yml
- README.md
SonarCloud badges.  Probably too many.
---
[Backend](https://quickstart-openshift-1250-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1250-frontend.apps.silver.devops.gov.bc.ca/) available
> Tons of badges for frontend and backend

- backend-java/pom.xml
Quarkus 3.3+ isn't working for us.  This looks like a known issue that might even have a fix around the corner!  :)
https://github.com/quarkusio/quarkus/pull/35732
---
- [Frontend](https://quickstart-openshift-1380-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1380-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-1380-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-1380-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-1380-backend-go.apps.silver.devops.gov.bc.ca)
- [Analysis …
> bug: dial back Quarkus to 3.2.4.Final

- .github/workflows/merge-main.yml
SchemaSpy is currently failing.  This comments it out, doing absolutely nothing to resolve the problem.
Issue for actualy fixing SchemaSpy: https://github.com/bcgov/quickstart-openshift/issues/1392
---
- [Frontend](https://quickstart-openshift-1393-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1393-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-1393-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-1393-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-1393-backend-go.apps.silver.devops.gov.bc.ca)
- [Analysis …
> chore: comment out schemaspy until fixed

- .github/workflows/analysis.yml
I took Om's advice, slashing CodeQL's Java analysis time:
Before: 8:54 (average)
Now: 2:26 (one run)
Thanks a bunch @mishraomp!  :D
---
- [Frontend](https://quickstart-openshift-1398-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1398-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-1398-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-1398-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-1398-backend-go.apps.silver.devops.gov.bc.ca)
- [Analysis Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/analy …
> feat: speed up code ql java

- backend/Dockerfile
- frontend/Caddyfile
- frontend/Dockerfile
- Move static files to `/src` for Frontend Caddy, the standard/expected location
- Suppress node update messages in Dockerfiles, not our problem
- Format Caddyfile for tabs over spaces, expected format (which I hate!)
---
- [Frontend](https://quickstart-openshift-1388-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1388-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-1388-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-1388-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-1388-backend-go.apps.silver.devops.gov.bc.ca)
- …
> feat: adjust node and caddy, align with caddy defaults

- .github/workflows/merge.yml
- .github/workflows/pentests.yml
- .github/workflows/pr-open.yml
Move penetration tests to a scheduled job instead of main merge.
---
- [Frontend](https://quickstart-openshift-1463-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1463-backend.apps.silver.devops.gov.bc.ca/api)
> feat: scheduled penetration tests

- .github/workflows/merge.yml
- .github/workflows/scheduled.yml
---
- [Frontend](https://quickstart-openshift-1465-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1465-backend.apps.silver.devops.gov.bc.ca/api)
> ci: move SchemaSpy and PenTests into scheduled.yml

- .github/workflows/merge.yml
Migrations haven't been getting promoted to PROD, just using TEST.
---
- [Frontend](https://quickstart-openshift-1466-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1466-backend.apps.silver.devops.gov.bc.ca/api)
> bug: promote migrations

- .github/workflows/merge.yml
- .github/workflows/pr-open.yml
* update builder action
* use `keep_versions` to only keep last 50 builds
* remove `build_file` handled by builder default
---
- [Frontend](https://quickstart-openshift-1467-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1467-backend.apps.silver.devops.gov.bc.ca/api)
> feat: ghcr cleanup at build time

- .github/workflows/pr-open.yml
- .github/workflows/pr-purge.yml
Delete pods, images and pvs once they hit two days old.
Currently runs by workflow_dispatch.  Cronjob provided, but commented out.
Command modified from [StackExchange](https://stackoverflow.com/questions/48934491/kubernetes-how-to-delete-pods-based-on-age-creation-time) and Linux [date app](https://tecadmin.net/getting-yesterdays-date-in-bash/).
---
- [Frontend](https://quickstart-openshift-1494-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1494-frontend.apps.silver.devops.gov.bc.ca/api)
- …
> feat: age out Pull Request environments

- .github/workflows/pr-open.yml
Since PR titles are used as merge messages they should follow conventional commits.  The included action will enforce that.
Stolen from @paulushcgcj.
---
- [Frontend](https://quickstart-openshift-1504-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1504-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: enforce conventional commits

- .github/workflows/merge.yml
- .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1505-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1505-frontend.apps.silver.devops.gov.bc.ca/api)
> ci: tag instead of release after PROD deploy

- .github/workflows/.deploy.yml
- .github/workflows/merge.yml
- .github/workflows/pr-open.yml
- charts/quickstart-openshift/Chart.lock
Helm jobs can collide due to timing or getting stuck.  This is intended to interrupt that.
---
- [Frontend](https://quickstart-openshift-1517-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1517-frontend.apps.silver.devops.gov.bc.ca/api)
---
- [Frontend](https://quickstart-openshift-1517-frontend.apps.silver.devops.gov.bc.ca) …
> fix: helm collisions

- charts/quickstart-openshift/values-pr.yaml
- charts/quickstart-openshift/values.yaml
Flyway doesn't yet support Postgres 16.  This PR dials it down to 15.4.0.
---
- [Frontend](https://quickstart-openshift-1525-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1525-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: postgres and flyway version mismatch

- .github/workflows/pr-close.yml
- .github/workflows/pr-open.yml
- frontend/Dockerfile
Now that Helm requires `${{github.sha}}` tags we can drop the ones for PR numbers.
---
- [Frontend](https://quickstart-openshift-1523-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1523-frontend.apps.silver.devops.gov.bc.ca/api)
> ci: tagging

- .github/workflows/pr-close.yml
- .github/workflows/pr-open.yml
- frontend/Dockerfile
This idea was a bit of a dud.  PR cleanup broke and we have upcoming changes in this space, so if it's not going to be quick, it should be dropped.
Reverts bcgov/quickstart-openshift#1523
---
- [Frontend](https://quickstart-openshift-1527-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1527-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: Revert "ci: tagging"

- .github/workflows/.deploy.yml
- README.md
- charts/quickstart-openshift/values-pr.yaml
- charts/quickstart-openshift/values.yaml
---
- [Frontend](https://quickstart-openshift-1535-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1535-frontend.apps.silver.devops.gov.bc.ca/api)
> chore: helm rollout check with digest

- .github/workflows/pr-close.yml
- .github/workflows/pr-open.yml
- .github/workflows/scheduled.yml
---
- [Frontend](https://quickstart-openshift-1496-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1496-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: delete Helm PR releases older than a week

- charts/quickstart-openshift/Chart.lock
- charts/quickstart-openshift/Chart.yaml
- charts/quickstart-openshift/values.yaml
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior
---
- [Frontend](https://quickstart-openshift-1565-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1565-frontend.apps.silver.devops.gov.bc.ca/api)
> feat(helm): Add support for scaling behavior

- .github/workflows/.merge.yml
Could create collisions, like a job which requires a deployment being interrupted by one that doesn't.
---
- [Frontend](https://quickstart-openshift-1602-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1602-frontend.apps.silver.devops.gov.bc.ca/api)
> ci: disable main merge cancel-in-progress

- .github/workflows/.deploy.yml
- .github/workflows/.merge.yml
- .github/workflows/.tests.yml
- .github/workflows/pr-open.yml
Save on resources by only deploying when triggers are met.  Omitting triggers always causes a deploy.
---
- [Frontend](https://quickstart-openshift-1608-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1608-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: add PR deploy triggers

- .github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-1614-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1614-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: cleanup fails on PR with no deploy

- .github/workflows/merge.yml
* improve scrubbing of last commit for PR number (had been failing on multiline)
* kick up errors when merging directly to main (which is bad!)
* workflow_dispatch, currently accepting PR numbers
---
- [Frontend](https://quickstart-openshift-1649-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1649-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: main merge workflow dispatch and error handling

- .github/workflows/merge.yml
- .github/workflows/pr-open.yml
Gets PR numbers in merge queues and squash merges.
---
- [Frontend](https://quickstart-openshift-1701-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1701-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: PR number action

- .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1706-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1706-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: only interrupt PRs, not merge queues

- .github/workflows/notifications.yml
Supporting MS Teams Notifications via workflow_run events!! 
- Triggers based on workflow status
Alerts at the Job/Step level in a workflow arn't really what was wanted.  
Alerts whenever workflows are triggered is useful to devs watching the channels to see pr->merge->deploy status
> feat: Adding notifications to ping teams of deployment workflow status

- README.md
Docs, links
- [X ] This change requires a documentation update
---
- [Frontend](https://quickstart-openshift-1766-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1766-frontend.apps.silver.devops.gov.bc.ca/api)
> docs: links to kickstart page is now updated.

- .github/workflows/analysis.yml
Converting to draft now interrutps the Analysis workflow.
---
- [Frontend](https://quickstart-openshift-1771-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1771-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: interrupt analysis w/ draft status

- .github/workflows/scheduled.yml
1. remove deprecated action
2. update schemaspy command to use pgsql 11 or later
---
- [Frontend](https://quickstart-openshift-1776-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1776-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: schema spy

- .github/workflows/scheduled.yml
Handle grep failing empty returns.  Add additional error handling, since `|| true` can hide problems.
NOTE: `|| :` is an alternative to `|| true` that cannot spawn processes.
---
- [Frontend](https://quickstart-openshift-1778-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1778-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(ci): PR environment purge

- .github/workflows/analysis.yml
- .github/workflows/pr-open.yml
- README.md
Adds complication, not compatible with new analysis workflow, not even useful for most teams.  Removing.
---
- [Frontend](https://quickstart-openshift-1783-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1783-frontend.apps.silver.devops.gov.bc.ca/api)
> chore(ci): remove merge queues

- .github/workflows/analysis.yml
- .github/workflows/pr-init.yml
- .github/workflows/pr-open.yml
- .github/workflows/pr-validate.yml
---
- [Frontend](https://quickstart-openshift-1781-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1781-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(ci): introduce pr validate/edit workflow

- .github/workflows/pr-validate.yml
PR Validate, which handles conventional commits and PR descriptions, runs more than necessary.  Opened, reopened and edited are enough.  Synchronize has been removed, which triggers on pushes.
---
- [Frontend](https://quickstart-openshift-1796-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1796-frontend.apps.silver.devops.gov.bc.ca/api)
> chore(ci): remove pr:synchronize trigger from pr-validate

- .github/workflows/analysis.yml
CodeQL job and scan result have the same name.  This renames the one we check to `CodeQL Security Scan`, making it easier to set up in branch protection rules.
---
- [Frontend](https://quickstart-openshift-1800-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1800-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: rename CodeQL job for easier selection

- .github/workflows/merge.yml
I forgot about merge.yml!  Whoops...
---
- [Frontend](https://quickstart-openshift-1854-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1854-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(ci): merge workflow deploys

- .github/workflows/merge.yml
- .github/workflows/pr-open.yml
- charts/app/templates/_helpers.tpl
- charts/app/templates/secret.yaml
- charts/app/values.yaml
---
- [Frontend](https://quickstart-openshift-1862-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1862-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: autoscaling and secrets

- charts/app/templates/backend/templates/deployment.yaml
- charts/app/templates/frontend/templates/deployment.yaml
- frontend/src/components/Dashboard.tsx
---
- [Frontend](https://quickstart-openshift-1858-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1858-frontend.apps.silver.devops.gov.bc.ca/api)
> chore: test PR subsequent commits

- .github/workflows/pr-close.yml
- .github/workflows/pr-open.yml
- .github/workflows/scheduled.yml
PR open and close should interrupt each other.  Their groups weren't matching.  Also added bitnami pvc to schedule cleanup job.
---
- [Frontend](https://quickstart-openshift-1874-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1874-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(ci): cleanup failures (concurrency)

- .github/workflows/pr-open.yml
Commas causing triggers not to fire.  This isn't the first time I've goofed, so maybe we should handle commas or at least kick up an error?
---
- [Frontend](https://quickstart-openshift-1883-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1883-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(ci): remove trigger commas

- frontend/package-lock.json
- frontend/package.json
- tests/integration/package-lock.json
- tests/integration/package.json
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/125
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/126
- https://github.com/bcgov/quickstart-openshift/security/dependabot/53
- https://github.com/bcgov/quickstart-openshift/security/dependabot/54
---
- [Frontend](https://quickstart-openshift-1882-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1882-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore(ci): bump axios for follow-redirects vulnerability

- .github/workflows/.tests.yml
- .github/workflows/pr-open.yml
- .github/workflows/scheduled.yml
Only run PR tests (integration, e2e, load)  if a deployment has happened and there's actually something to test.
---
- [Frontend](https://quickstart-openshift-1885-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1885-frontend.apps.silver.devops.gov.bc.ca/api)
---
- [Frontend](https://quickstart-openshift-1885-frontend.apps.silver.de …
> chore(ci): run PR tests conditionally

- backend/package-lock.json
- backend/package.json
Fixes eslint-plugin-n dep conflict.
---
- [Frontend](https://quickstart-openshift-1891-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1891-frontend.apps.silver.devops.gov.bc.ca/api)
> chore(deps): bump eslint-plugin-n

- .github/workflows/pr-validate.yml
PRs don't need to be validated while in draft status.
---
- [Frontend](https://quickstart-openshift-1895-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1895-frontend.apps.silver.devops.gov.bc.ca/api)
> feat(ci): only validate ready PRs (not draft)

- frontend/cypress.config.ts
- frontend/cypress/e2e/user-table.cy.ts
- frontend/src/components/Dashboard.tsx
---
- [Frontend](https://quickstart-openshift-1922-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1922-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: Cypress e2e, with explicit ID while looking for HTML elements.

- .github/workflows/merge.yml
- .github/workflows/pr-close.yml
- .github/workflows/pr-open.yml
- .github/workflows/pr-validate.yml
---
- [Frontend](https://quickstart-openshift-1926-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1926-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: missing deploy outputs

- .github/workflows/scheduled.yml
For Helm cleanup there have been unimportant, but ugly errors when there are no bitnami PVCs to clean up.  This PR adds `|| true` for that case.
---
- [Frontend](https://quickstart-openshift-1936-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1936-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(ci): handle no bitnami pvc in cleanup

- .github/workflows/analysis.yml
- .github/workflows/codeql.yml
GitHub now likes to create their own CodeQL workflow that conflicts with ours.  Since theirs works just fine, let's go with it!
---
- [Frontend](https://quickstart-openshift-1945-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1945-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(ci): codeql collision

- .github/workflows/scheduled.yml
- docker-compose.yml
---
- [Frontend](https://quickstart-openshift-1957-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1957-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(schemaspy): default schema

- frontend/cypress/e2e/home-page.cy.ts
- frontend/src/components/Header.tsx
---
- [Frontend](https://quickstart-openshift-1958-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1958-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(frontend): header title color

- backend/.dockerignore
- backend/Dockerfile
- backend/package-lock.json
- backend/package.json
- docker-compose.yml
- frontend/.dockerignore
- frontend/Caddyfile
- frontend/Dockerfile
- frontend/package.json
Simplifications and making Dockerfiles more generic.  Unfortunately `docker compose watch` isn't going to work very easily with our Distroless and Caddy containers.
---
- [Frontend](https://quickstart-openshift-2002-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2002-frontend.apps.silver.devops.gov.bc.ca/api)
> feat(ci): compose watch and docker simplification

- frontend/Caddyfile
---
- [Frontend](https://quickstart-openshift-2010-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2010-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(frontend): remove trailing slash from caddy proxy

- charts/app/templates/backend/templates/deployment.yaml
- charts/app/templates/secret.yaml
- charts/app/values.yaml
---
- [Frontend](https://quickstart-openshift-2011-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2011-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(helm): make different secrets for backend, postgres DB and flyway and remove unnecessary secret entries

- charts/app/values.yaml
postgis extension was being enabled on postgis database, suspect that it needs on the app "quickstart" database
Changed the database that the bitnami postgis extension is being enabled on.
In related repo that used this template found that the postgis extension wasn't available on the user database that was created.
```
SELECT name, default_version,installed_version FROM pg_available_extensions WHERE name LIKE 'postgis%' ;
SELECT PostGIS_Full_Version();
```
---
- [Frontend](https://quickstart-openshift-2042-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2042-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
> fix: create postgis extension on the app database

- renovate.json
Renovaete isn't picking up tests/integration/package.json.  This could be due to a preset, which is being disabled for testing.  If successful this will come back up, but get bumpted up to bcgov/renovate-config.
---
- [Frontend](https://quickstart-openshift-2053-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2053-frontend.apps.silver.devops.gov.bc.ca/api)
> chore(ci): adjust renovate for all package.json files

- backend/Dockerfile
- backend/nest-cli.json
- backend/package-lock.json
- backend/package.json
---
- [Frontend](https://quickstart-openshift-2094-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2094-frontend.apps.silver.devops.gov.bc.ca/api)
> feat(backend): swc (faster compile and dev)

- .github/workflows/notifications.yml
Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.
---
- [Frontend](https://quickstart-openshift-2100-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2100-frontend.apps.silver.devops.gov.bc.ca/api) …
> feat: ms teams notifications logic from onroutebc

- README.md
---
- [Frontend](https://quickstart-openshift-2126-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2126-frontend.apps.silver.devops.gov.bc.ca/api)
> docs: remove pluggable backends

- .github/workflows/.dbdeployer.yml
---
- [Frontend](https://quickstart-openshift-2138-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2138-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: db deployer better check for pr handle

- .github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-2142-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2142-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: crunchydb remove user and db when pr is closed.

- .github/workflows/.dbdeployer.yml
- .github/workflows/pr-close.yml
- .github/workflows/pr-open.yml
- README.md
- charts/app/Chart.lock
- charts/app/Chart.yaml
- charts/app/templates/_helpers.tpl
- charts/app/templates/secret.yaml
- charts/app/values.yaml
---
- [Frontend](https://quickstart-openshift-2150-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2150-frontend.apps.silver.devops.gov.bc.ca/api)
> chore: add params to make crunchy optional, and document the steps needed.

- .github/workflows/analysis.yml
Trivy has been having problems, so it has been removed from Analysis Results needs in analysis.yml.  Ideally this can be restored when they're no longer having issues.
```
results:
name: Analysis Results
if: always()
needs: [..., trivy] # Restore trivy when/if fixed
```
---
- [Frontend](https://quickstart-openshift-2165-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2165-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflo …
> fix(ci): allow trivy to fail (temporary)

- .github/workflows/pr-close.yml
- .github/workflows/pr-open.yml
- .github/workflows/scheduled.yml
---
- [Frontend](https://quickstart-openshift-2168-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2168-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: SchemaSpy shared workflow

- charts/app/templates/frontend/templates/deployment.yaml
---
- [Frontend](https://quickstart-openshift-2177-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2177-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: adding volumes to caddy

- .github/workflows/.deployer.yml
Make Crunchy deploy before the rest of the stack.  Avoids retries.
---
- [Frontend](https://quickstart-openshift-2184-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2184-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: deploy db before stack

- .github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-2206-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2206-frontend.apps.silver.devops.gov.bc.ca/api)
> ci: merge workflow_dispatch input

- charts/app/templates/backend/templates/deployment.yaml
- charts/app/templates/frontend/templates/deployment.yaml
- charts/app/values.yaml
- charts/crunchy/templates/PostgresCluster.yaml
- charts/crunchy/values.yaml
Remove limits as it is removed from the OpenShift Platform
---
- [Frontend](https://quickstart-openshift-2218-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2218-frontend.apps.silver.devops.gov.bc.ca/api)
> chore: remove limits

- .github/workflows/scheduled.yml
---
- [Frontend](https://quickstart-openshift-2226-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2226-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(ci): catch missing oc action after gh runner update

- charts/crunchy/values.yaml
---
- [Frontend](https://quickstart-openshift-2230-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2230-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: remove explicit crunchy images

- charts/app/values.yaml
---
- [Frontend](https://quickstart-openshift-2232-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2232-frontend.apps.silver.devops.gov.bc.ca/api)
> chore: add rate limiting to openshift frontend routes

- .github/workflows/.deployer.yml
- .github/workflows/merge.yml
- .github/workflows/pr-close.yml
- .github/workflows/pr-open.yml
- .github/workflows/scheduled.yml
---
- [Frontend](https://quickstart-openshift-2215-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2215-frontend.apps.silver.devops.gov.bc.ca/api)
> ci: simplify and cleanup

- .github/workflows/.deployer.yml
- .github/workflows/merge.yml
- .github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-2236-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2236-frontend.apps.silver.devops.gov.bc.ca/api)
> fix(ci): unnecessary param, allow pr-open to skip fail on no db user

- .github/workflows/.deployer-db.yml
- .github/workflows/.deployer.yml
- .github/workflows/demo.yml
- .github/workflows/pr-close.yml
- .github/workflows/pr-open.yml
- .github/workflows/scheduled.yml
---
- [Frontend](https://quickstart-openshift-2240-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2240-frontend.apps.silver.devops.gov.bc.ca/api)
> feat(ci): use action-oc-runner

- .github/workflows/demo.yml
- .github/workflows/scheduled.yml
Consistently use GH runner ubuntu-24.04 everywhere.  This is more explicit than ubuntu-latest and doesn't create annotation warnings when latest is updated.
---
- [Frontend](https://quickstart-openshift-2249-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2249-frontend.apps.silver.devops.gov.bc.ca/api)
> chore(ci): consistently use GH runner ubuntu-24.04

- .github/workflows/pr-close.yml
---
thanks to @Scarlett-Truong and @jon-funk , copied from here
https://github.com/bcgov/nr-compliance-enforcement/pull/941
---
- [Frontend](https://quickstart-openshift-2283-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2283-frontend.apps.silver.devops.gov.bc.ca/api)
---
- …
> fix: pipe the drop command to avoid edge cases and reconnection issues

- charts/app/values.yaml
---
- [Frontend](https://quickstart-openshift-2294-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2294-frontend.apps.silver.devops.gov.bc.ca/api)
> fix: add roundrobin to frontend route

- .github/workflows/scheduled.yml
Fix scheduled job while trying not to repeat too much code. (DRY = don't repeat yourself)
---
- [Frontend](https://quickstart-openshift-2322-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2322-frontend.apps.silver.devops.gov.bc.ca/api)
> chore(ci): scheduled job fix

- .github/workflows/scheduled.yml
Permissions changes.  ZAP gets `issues: write` and SchemaSpy gets `contents: write`.
---
- [Frontend](https://quickstart-openshift-2323-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2323-frontend.apps.silver.devops.gov.bc.ca/api)
> chore(ci): SchemaSpy and ZAP permissions

- .github/workflows/analysis.yml
Bug squashed in action PR.  
https://github.com/bcgov/action-test-and-analyse/pull/66
New release updated here.
---
- [Frontend](https://quickstart-openshift-2352-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2352-frontend.apps.silver.devops.gov.bc.ca/api)
---
- [Frontend](https://quickstart-openshift-2352-frontend.apps.silver.dev …
> chore(ci): bump actoin-test-and-analyse for bug

- frontend/package-lock.json
- frontend/package.json
eslint-plugin-yaml@1.03 was the culprit.   It doesn't appear to be used anywhere and has been removed.
---
- [Frontend](https://quickstart-openshift-2429-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2429-frontend.apps.silver.devops.gov.bc.ca/api)
> chore(deps): npm unsupported URL type - link

- .github/workflows/.deployer.yml
- backend/src/prisma.service.ts
- charts/app/templates/secret.yaml
- charts/crunchy/values.yml
---
- [Frontend](https://quickstart-openshift-2440-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2440-frontend.apps.silver.devops.gov.bc.ca/api)
> chore: use pgbouncer for connection pooling which handles crunchy failover better than prisma pool

- .github/workflows/.deployer.yml
- .github/workflows/pr-open.yml
- backend/src/prisma.service.ts
- charts/app/templates/backend/templates/deployment.yaml
- charts/crunchy/values.yml
---
- [Frontend](https://quickstart-openshift-2442-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2442-frontend.apps.silver.devops.gov.bc.ca/api)
> chore: remove db queries from health check and fix local access to crunchy through pgbouncer when port forwarding
