bcgov/quickstart-openshift

Dockerfile
Minimized image to be 112 MB in size
=> feat:Dockerfile installs nodejs

.github/workflows/pr.yml, Dockerfile
Installs nodejs v14.  Can only do this from RH UBI, there's no means to access v14 from microdnf.  Image weighs in at 411 MB
=> feat:nodejs14

Dockerfile
Dockerfile stages RH UBI images.  Has to construct in UBI, then copy to micro UBI.  Resulting image weighs in at 85.2 MB
=> feat: nodejs14 on micro

package-lock.json, package.json
Addresses https://github.com/bcgov-nr/greenfield-pipeline/pull/85.
=> Update nestjs for node-fetch dependabot warning

package-lock.json, package.json
Addresses https://github.com/bcgov/greenfield-template/pull/134
=> Deps - bump nestjs for axios for follow-redirects

.github/workflows/pr-open.yml
Reverts bcgov/greenfield-template#163
=> Revert "Update pr-open.yml"

.github/workflows/pr-close.yml
=> Clean up old packages from ghcr.io

.github/workflows/pr-open.yml, backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json
E.g.
```
"overrides": {
"minimist": "1.2.6"
}
}
```
=> Address dep/minimist with override, not requirement

.github/pipeline/deploy.backend.yml, .github/pipeline/deploy.frontend.yml
Envars for DATABASE_URL and BACKEND_URL.
=> Envars for finding backend, database

.github/workflows/main.yml, .github/workflows/pr-open.yml
Specify Actions versions and tighten up settings (done outside of PR).
https://engineering.salesforce.com/github-actions-security-best-practices-b8f9df5c75f5
=> Follow Security Guide

backend/package-lock.json, backend/package.json
Upgraded version of @nestjs/swagger
=> Upgraded version of @nestjs/swagger

README.md
update README.md with a link to the IIT-ARCH repo for example APIs.
Documentation update.
=> update README.md with link to IIT-ARCH repo for example APIs.

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml
Reintroduce Sonarcloud to PR and main merge workflows.
=>  Reenable Sonarcloud

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml, frontend/src/app.controller.spec.ts, frontend/src/app.service.ts, frontend/test/app.e2e-spec.ts
Stop replacing databases unnecessarily.  This only creates if one doesn't exist.
=> Only create db if necessary

.github/workflows/merge-main.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml
Make workflow runners consistently use ubuntu-22.04. Had mostly been using ubuntu-latest, with a few leftovers on ubuntu-18.04.
=> Use ubuntu-22.04 across all workflows

.github/openshift/deploy.backend.yml, .github/openshift/deploy.database.yml, .github/openshift/deploy.frontend.yml, .github/openshift/networkPolicies.yml, .github/workflows/merge-main.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml, README.md, SECURITY.md, SETUP.md, backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json
This and the helper repo have been renamed.  Hopefully for the last time!  ...for a while.
=> Repo rename

.github/workflows/merge-main.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml
Overhaul pipeline to use nr-quickstart-helpers@v0.0.2 wherever practical.
<p>
---
[Backend](https://nr-quickstart-helpers-538-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-helpers-538-frontend.apps.silver.devops.gov.bc.ca/) available
=> Overhaul for nr-quickstart-helpers@v.0.0.2

.github/workflows/pr-open.yml
For forks pull request changer requires token to have permissions.pull-requests=write to make changes.
=> Provide token pull-requests=write permissions

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml, backend/openshift.deploy.yml, frontend/openshift.deploy.yml
1. Add HPA to both backend and frontend deployment.
2. Add CPU and Memory Limits
3. Parameterize the min and max replicas for HPA.
- [X ] New feature (non-breaking change which adds functionality)
not tested.
---
[Backend](https://nr-quickstart-helpers-556-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-helpers-556-frontend.apps.silver.devops.gov.bc.ca/) available
=> Adding HPA and associated changes

.github/workflows/merge-main.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml
---
[Backend](https://nr-quickstart-typescript-557-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-557-frontend.apps.silver.devops.gov.bc.ca/) available
=> Workflow var revision and overall cleanup

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml
Combine SonarCloud jobs using a matrix.  Likely prepare it for a helper workflow.
=> SonarCloud simplify and use matrices

.github/workflows/merge-main.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml, common/openshift.init.yml
---
[Backend](https://nr-quickstart-typescript-591-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-591-frontend.apps.silver.devops.gov.bc.ca/) available
=> Misc cleanup and corrections

.github/workflows/pr-open.yml, docker-compose.yml
[secret-search](https://github.com/marketplace/actions/secret-search).  Uses Yelp's detect-secrets.  Standalone, so no account or token are required.
---
[Backend](https://nr-quickstart-typescript-599-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-599-frontend.apps.silver.devops.gov.bc.ca/) available
=> Secret-search in PR workflow

README.md
Badges:
- Merge to Main
- Unit Tests and Analysis
Skipped PR workflows, since too noisy.  Idea: script for updating badges, since no vars in markdown.  (sort of-to-mostly)
---
[Backend](https://nr-quickstart-typescript-609-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-609-frontend.apps.silver.devops.gov.bc.ca/) available
=> PR and 3x workflow badges

.github/workflows/pr-open.yml
Consume the new build action. Lots of small changes.
---
[Backend](https://nr-quickstart-typescript-610-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-610-frontend.apps.silver.devops.gov.bc.ca/) available
=> Use bcgov-nr/action-conditional-container-builder@v0.0.1

.github/workflows/pr-open.yml
---
[Backend](https://nr-quickstart-typescript-612-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-612-frontend.apps.silver.devops.gov.bc.ca/) available
=> Point to new org for action-pr-description-add

.github/workflows/pr-open.yml
```
builds:
name: Builds
runs-on: ubuntu-latest
permissions:
packages: write
```
---
[Backend](https://nr-quickstart-typescript-614-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-614-frontend.apps.silver.devops.gov.bc.ca/) available
=> Token permissions.packages=write for Dependabot

.github/workflows/merge-main.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml
Composite action.
https://github.com/bcgov-nr/action-deployer-openshift
---
[Backend](https://nr-quickstart-typescript-616-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-616-frontend.apps.silver.devops.gov.bc.ca/) available
=> Consume bcgov-nr/action-deployer-openshift@v0.0.1

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml, .github/workflows/unit-tests.yml
Compsite Action for unit tests and sonarcloud.
https://github.com/bcgov-nr/action-test-and-analyse
---
[Backend](https://nr-quickstart-typescript-619-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-619-frontend.apps.silver.devops.gov.bc.ca/) available
=> Consume bcgov-nr/action-test-and-analyse@v0.0.1

.github/workflows/pr-open.yml
---
[Backend](https://nr-quickstart-typescript-622-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-622-frontend.apps.silver.devops.gov.bc.ca/) available
=> Update action name

backend/Dockerfile, database/Dockerfile, database/postgis/Dockerfile, frontend/Dockerfile
4x don't use root user in Dockerfiles
---
[Backend](https://nr-quickstart-typescript-631-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-631-frontend.apps.silver.devops.gov.bc.ca/) available
=> Dockerfiles - unprivileged users

.github/workflows/merge-main.yml
---
[Backend](https://nr-quickstart-typescript-669-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-669-frontend.apps.silver.devops.gov.bc.ca/) available
=> Removed trivy prereq in main-merge.yml

.github/workflows/merge-main.yml, backend/openshift.deploy.yml, frontend/openshift.deploy.yml
Image retagging from test to prod had been missed.
---
[Backend](https://nr-quickstart-typescript-774-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-774-frontend.apps.silver.devops.gov.bc.ca/) available
=> Add retag for prod db

.github/workflows/pr-open.yml
Remove Secret Search/Scan by Yelp.  Functionality replaced by Trivy, which is already handling vulnerability and config scanning.  Lightens our Actions usage slightly.
=> Secret Search/Scan replaced by Trivy secret scanning

renovate.json
Batch renovate PRs.  Config copied from bcgov/wps.  Thanks @conbrad!
---
[Backend](https://nr-quickstart-typescript-853-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-853-frontend.apps.silver.devops.gov.bc.ca/) available
=> Batch Renovate PRs (from bcgov/wps)

frontend-react/package.json, frontend-react/yarn.lock
Resolves #900 
Blocking #899 
---
[Backend](https://nr-quickstart-typescript-901-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-901-frontend.apps.silver.devops.gov.bc.ca/) available
=> Update parent for http-cache-semantics@4.1.1

backend/Dockerfile, database/Dockerfile, docker-compose.yml, frontend-react/Dockerfile, frontend/Dockerfile
#902 
---
[Backend](https://nr-quickstart-typescript-905-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-905-frontend.apps.silver.devops.gov.bc.ca/) available
=> Docker Compose and OpenShift attempted parity

backend/Dockerfile, database/postgis/Dockerfile
More Docker adjustments.  Will make Trivy Action happy.
---
[Backend](https://nr-quickstart-typescript-907-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-907-frontend.apps.silver.devops.gov.bc.ca/) available
=> Docker tweaks

backend/Dockerfile
---
[Backend](https://nr-quickstart-typescript-1083-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-1083-frontend.apps.silver.devops.gov.bc.ca/) available
=> Add Heap Size to Dockerfile for backend container

.github/workflows/unit-tests.yml, backend/src/app.module.ts, backend/src/users/entities/users.entity.ts, backend/src/users/users.controller.spec.ts, backend/src/users/users.controller.ts, backend/src/users/users.service.spec.ts, backend/src/users/users.service.ts, docker-compose.yml
---
[Backend](https://nr-quickstart-typescript-1088-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-1088-frontend.apps.silver.devops.gov.bc.ca/) available
=> Add, search, pagination and sort capabilities in api through search endpoint.

.github/workflows/unit-tests.yml, README.md, SECURITY.md, backend/openshift.deploy.yml, backend/package-lock.json, backend/package.json, common/openshift.init.yml, database/openshift.deploy.yml, database/templates/openshift.deploy.yml, frontend-react/README.md, frontend-react/package.json, frontend/openshift.deploy.yml
---
[Backend](https://quickstart-openshift-1092-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1092-frontend.apps.silver.devops.gov.bc.ca/) available
=> Code changes from repo rename

backend/package.json, frontend-react/package.json, frontend/package.json
Remove repo references and `private: true`, change author to FSA, in 3x package.json.  This minimizes the likelihood that npmjs.com package can be published with references to incorrect repos or authors.
---
[Backend](https://quickstart-openshift-1095-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1095-frontend.apps.silver.devops.gov.bc.ca/) available
=> Clean up 3x package.json

.github/workflows/merge-main.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml, backend/db/Dockerfile, backend/db/migrations/V1.0.0__init.sql, backend/openshift.deploy.yml, backend/src/app.module.ts, docker-compose.yml, frontend/package-lock.json
Add flyway init-container pattern
---
[Backend](https://quickstart-openshift-1099-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1099-frontend.apps.silver.devops.gov.bc.ca/) available
=> Flyway DB migrations

.github/workflows/merge-main.yml
---
[Backend](https://quickstart-openshift-1105-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1105-frontend.apps.silver.devops.gov.bc.ca/) available
=> fixing the merge main workflow

backend/Dockerfile, database/Dockerfile, frontend-react/Dockerfile, frontend/Dockerfile
Dockerfiles: remove digests, minor version update
---
[Backend](https://quickstart-openshift-1117-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1117-frontend.apps.silver.devops.gov.bc.ca/) available
=> Stop using Dockerfile digests, plus minor version updates

.github/workflows/merge-main.yml
---
[Backend](https://quickstart-openshift-1121-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1121-frontend.apps.silver.devops.gov.bc.ca/) available
=> change schema to lowercase

database/postgis/Dockerfile, docker-compose.yml
---
[Backend](https://quickstart-openshift-1131-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1131-frontend.apps.silver.devops.gov.bc.ca/) available
=> Clip digests

.github/workflows/unit-tests.yml, backend-python/poetry.lock, backend-python/pyproject.toml, backend-python/run-unit-tests.sh, backend-python/test/test_main.py
---
[Backend](https://quickstart-openshift-1138-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1138-frontend.apps.silver.devops.gov.bc.ca/) available
=> Add unit tests for python backend API

.github/workflows/pr-open.yml
Support deployment triggers, like in bcgov-nr/action-builder-ghcr.
---
[Backend](https://quickstart-openshift-1150-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1150-frontend.apps.silver.devops.gov.bc.ca/) available
=> Feat: Deployment Triggers

backend-java/pom.xml, backend-java/src/test/java/ca/bc/gov/nrs/api/helpers/TestHelper.java, backend-java/src/test/java/ca/bc/gov/nrs/api/v1/endpoints/UserEndpointTest.java
---
[Backend](https://quickstart-openshift-1170-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1170-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix test method names and also add some more test cases.

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml, backend-java/openshift.deploy.yml, backend-python/openshift.deploy.yml, backend/openshift.deploy.yml, frontend/openshift.deploy.yml
---
[Backend](https://quickstart-openshift-1162-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1162-frontend.apps.silver.devops.gov.bc.ca/) available
=> Decrease the initial delay seconds.

.github/workflows/merge-main.yml
---
[Backend](https://quickstart-openshift-1174-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1174-frontend.apps.silver.devops.gov.bc.ca/) available
=> Upgrade to latest version for merge to main workflow.

backend/src/main.ts
---
[Backend](https://quickstart-openshift-1193-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1193-frontend.apps.silver.devops.gov.bc.ca/) available
=> Adding catch block to avoid sonar issue.

.github/workflows/merge-main.yml
---
[Backend](https://quickstart-openshift-1197-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1197-frontend.apps.silver.devops.gov.bc.ca/) available
=> Added missing verification path

backend/src/users/users.controller.ts, backend/src/users/users.service.spec.ts, backend/src/users/users.service.ts
---
[Backend](https://quickstart-openshift-1201-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1201-frontend.apps.silver.devops.gov.bc.ca/) available
=> bug fixes for findone endpoint

backend-python/poetry.lock, backend-python/pyproject.toml, backend-python/src/v1/routes/user_routes.py, docker-compose.py.yml
- added missing endpoints for get by id and delete by id
- fixed docker-compose for model generator
- updated a few dependencies
---
[Backend](https://quickstart-openshift-1208-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1208-frontend.apps.silver.devops.gov.bc.ca/) available
=> enhancements and dependency upgrades

backend-go/src/app.go
---
[Backend](https://quickstart-openshift-1212-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1212-frontend.apps.silver.devops.gov.bc.ca/) available
=> reorder the monitor middleware for swagger to work.

backend-python/src/v1/routes/user_routes.py
---
[Backend](https://quickstart-openshift-1210-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1210-frontend.apps.silver.devops.gov.bc.ca/) available
=> Added the mapping from DB obect to Struct

.github/workflows/merge-main.yml, backend-go/src/v1/routes/user-routes.go, backend-go/src/v1/services/user-service.go, integration-tests/package-lock.json, integration-tests/package.json, integration-tests/src/main.js, integration-tests/src/test_suites/it.backend.fastapi.json, integration-tests/src/test_suites/it.backend.fiber.json, integration-tests/src/test_suites/it.backend.nest.json, integration-tests/src/test_suites/it.backend.quarkus.json
1. workflow updates
2. bug fixes in apis
3. IT module.
---
[Backend](https://quickstart-openshift-1217-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1217-frontend.apps.silver.devops.gov.bc.ca/) available
=> code changes for integration tests

.github/workflows/merge-main.yml
---
[Backend](https://quickstart-openshift-1222-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1222-frontend.apps.silver.devops.gov.bc.ca/) available
=> workflow reorder and add dependencies(it,e2e) to prod deploy

CONTRIBUTING.md
Contributing: recommend branches over forks
---
[Backend](https://quickstart-openshift-1234-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1234-frontend.apps.silver.devops.gov.bc.ca/) available
=> Contributing: recommend branches over forks

.github/workflows/merge-main.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml
update workflows to avoid execution from forked PR and merge main to avoid run on pr close completion.
---
[Backend](https://quickstart-openshift-1272-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1272-frontend.apps.silver.devops.gov.bc.ca/) available
=> chore: Workflow Updates

.github/workflows/unit-tests.yml, .gitignore
Update action.  Adds test triggers (run/exit success).  There have been breaking changes.  Requires some changes to branch protection since JavaScript actions now run conditionally.
---
[Backend](https://quickstart-openshift-1293-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1293-frontend.apps.silver.devops.gov.bc.ca/) available
=> deps: v1.0.0 for bcgov-nr/action-test-and-analyse

.github/workflows/pr-open.yml
Deps
---
[Backend](https://quickstart-openshift-1295-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1295-frontend.apps.silver.devops.gov.bc.ca/) available
=> deps: update action-pr-descrption-add to v1.0.1

.github/workflows/merge-main.yml
---
[Backend](https://quickstart-openshift-1317-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1317-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat: zap pen tests create issues

backend-go/openshift.deploy.yml, backend-python/openshift.deploy.yml, backend/openshift.deploy.yml
---
[Backend](https://quickstart-openshift-1333-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://quickstart-openshift-1333-frontend.apps.silver.devops.gov.bc.ca/) available
=> Adjusted resources for init Containers

.github/workflows/merge-main.yml, backend/Dockerfile, database/Dockerfile, database/postgis/Dockerfile, frontend/Dockerfile, frontend/package-lock.json, frontend/package.json
Frontend and backend.  Drop Alpine, use Node Debian Slim for builds and either Caddy or Debian Distroless for deploys.
---
- [Frontend](https://quickstart-openshift-1355-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1355-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-1355-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-1355-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-1355-backend-go.apps.silver.devops.gov.bc.ca)
- …
=> feat: node consistency

.github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1365-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1365-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-1365-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-1365-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-1365-backend-go.apps.silver.devops.gov.bc.ca)
- [Tests Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/tests.yml)
After merge, new images are …
=> deps: bump builder action

.github/workflows/merge-main.yml, backend-go/openshift.deploy.yml, backend-java/openshift.deploy.yml, backend-py/openshift.deploy.yml, backend/openshift.deploy.yml, common/openshift.init.yml, database/openshift.deploy.yml, frontend/openshift.deploy.yml
Templates are supposed to have quotes around params.  Not required, but recommended.  From Snyk readings.
---
- [Frontend](https://quickstart-openshift-1375-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1375-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-1375-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-1375-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-1375-backend-go.apps.silver.devops.gov.bc.ca)
- [Tests …
=> feat: quote inputs

.github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1386-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1386-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-1386-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-1386-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-1386-backend-go.apps.silver.devops.gov.bc.ca)
- [Tests Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/tests.yml)
After merge, new images are …
=> deps: bump PR description action

.github/workflows/merge-main.yml
Leftover from my commenting out of jobs.
---
- [Frontend](https://quickstart-openshift-1396-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1396-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-1396-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-1396-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-1396-backend-go.apps.silver.devops.gov.bc.ca)
- [Tests Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows …
=> chore: indentation

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml, frontend/Dockerfile
---
- [Frontend](https://quickstart-openshift-1402-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1402-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-1402-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-1402-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-1402-backend-go.apps.silver.devops.gov.bc.ca)
- [Tests Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/tests.yml)
After merge, new images are …
=> deps: bump deployer

.github/workflows/merge-main.yml
---
- [Frontend](https://quickstart-openshift-1419-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1419-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-1419-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-1419-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-1419-backend-go.apps.silver.devops.gov.bc.ca)
- [Tests Workflow](https://github.com/bcgov/quickstart-openshift/actions/workflows/tests.yml)
After merge, new images are …
=> bug: ZAP issue duplication

docker-compose.yml, frontend/index.html
---
- [Frontend](https://quickstart-openshift-1423-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1423-backend.apps.silver.devops.gov.bc.ca)
=> feat: add caddy to docker-compose

README.md
---
- [Frontend](https://quickstart-openshift-1426-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1426-backend.apps.silver.devops.gov.bc.ca)
=> docs: pluggable backends

.github/workflows/pr-open.yml, database/Dockerfile
---
- [Frontend](https://quickstart-openshift-1440-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1440-backend.apps.silver.devops.gov.bc.ca)
=> ci: clip unnecessary checkout

.github/workflows/analysis.yml, .github/workflows/merge.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml
Timeouts added wherever possible.  Please not these values could use adjusting.
---
- [Frontend](https://quickstart-openshift-1448-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1448-backend.apps.silver.devops.gov.bc.ca)
=> feat: add timeouts to all jobs

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1462-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1462-backend.apps.silver.devops.gov.bc.ca/api)
=> bug: move environment value in merge.yml

frontend/package-lock.json, frontend/package.json
---
- [Frontend](https://quickstart-openshift-1488-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1488-backend.apps.silver.devops.gov.bc.ca/api)
=> feat: snyk warnings

.github/workflows/merge.yml
Don't promote code if Pull Request is only closed and is not merged to main.
---
- [Frontend](https://quickstart-openshift-1500-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1500-frontend.apps.silver.devops.gov.bc.ca/api)
=> dont promote code , if not merged.

.github/workflows/.deploy.yml
---
- [Frontend](https://quickstart-openshift-1520-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1520-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: default values yaml file name in the common .deploy.yml file

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1522-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1522-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: add prereq to main merge

.github/workflows/.deploy.yml, .github/workflows/merge.yml, .github/workflows/pr-open.yml, charts/quickstart-openshift/Chart.lock, charts/quickstart-openshift/Chart.yaml, charts/quickstart-openshift/values.yaml
---
- [Frontend](https://quickstart-openshift-1528-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1528-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: use image digests for conditional rollouts with HELM, initial attempt

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1529-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1529-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: merge workflow dependencies

.github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1534-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1534-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: step name

.github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-1547-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1547-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: cleanup step to remove Bitnami Crunchy PVCs

.github/workflows/.deploy.yml, charts/quickstart-openshift/templates/secret.yaml, charts/quickstart-openshift/values-pr.yaml
---
- [Frontend](https://quickstart-openshift-1550-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1550-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: make everything read from global secret.

charts/quickstart-openshift/templates/secret.yaml, charts/quickstart-openshift/values-pr.yaml, charts/quickstart-openshift/values.yaml
---
- [Frontend](https://quickstart-openshift-1552-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1552-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: merge workflow values file.

charts/quickstart-openshift/values-pr.yaml, charts/quickstart-openshift/values.yaml
---
- [Frontend](https://quickstart-openshift-1553-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1553-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: fix POSTGIS extension with correct script.

renovate.json
---
- [Frontend](https://quickstart-openshift-1556-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1556-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: extend Renovate config from bcgov/nr-renovate

renovate.json
---
- [Frontend](https://quickstart-openshift-1558-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1558-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: update Renovate repo

charts/quickstart-openshift/values.yaml
---
- [Frontend](https://quickstart-openshift-1567-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1567-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(helm): read the secret from correct place into Env var for backup container.

.github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-1569-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1569-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: handle misses in close workflow

.github/workflows/.deploy.yml, .github/workflows/.tests.yml, .github/workflows/merge.yml, .github/workflows/pr-open.yml
- Completed pod cleanup moved from main merge to deploy dispatch
- Move integration and e2e tests into a workflow dispatch
- Cleanup and simplification
- More in upcoming PRs!
---
- [Frontend](https://quickstart-openshift-1571-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1571-frontend.apps.silver.devops.gov.bc.ca/api)
---
- …
=> ci: simplify workflows

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1575-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1575-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: fix main merge workflow

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1576-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1576-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: fix PROD digest tags

.github/workflows/scheduled.yml
---
- [Frontend](https://quickstart-openshift-1579-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1579-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: fix scheduled job

.github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1583-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1583-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: fix build trigger

.github/workflows/.deploy.yml, .github/workflows/merge.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml, charts/quickstart-openshift/Chart.yaml, charts/quickstart-openshift/values.yaml
---
- [Frontend](https://quickstart-openshift-1570-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1570-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: trigger merge workflow on tag creation

.github/workflows/merge.yml, .github/workflows/pr-close.yml, renovate.json
---
- [Frontend](https://quickstart-openshift-1585-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1585-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: misc workflow fixes

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1586-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1586-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: test tag trigger

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1587-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1587-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: fix tag names

.github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-1589-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1589-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: skip retags when there is no new tag

.github/workflows/.deploy.yml, .github/workflows/.tests.yml, backend/package-lock.json, frontend/package-lock.json
---
- [Frontend](https://quickstart-openshift-1590-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1590-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(deps): lock file maintenance

charts/quickstart-openshift/Chart.yaml, charts/quickstart-openshift/values.yaml
---
- [Frontend](https://quickstart-openshift-1597-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1597-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(hpa): update version of helm-service to fix hpa issue

.github/workflows/.deploy.yml, .github/workflows/.merge.yml, .github/workflows/.tests.yml, .github/workflows/pr-close.yml, .github/workflows/scheduled.yml
---
- [Frontend](https://quickstart-openshift-1604-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1604-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: move image promotion to merge workflow

.github/workflows/.merge.yml
---
- [Frontend](https://quickstart-openshift-1607-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1607-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: disable semver skip on empty

.github/workflows/.deploy.yml
---
- [Frontend](https://quickstart-openshift-1609-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1609-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: deployer creating extra environments

.github/workflows/.deploy.yml, .github/workflows/.merge.yml
Still creating junk environments, so stop being cute and just pass the environment in as a parameter.  Plus cleanup.
---
- [Frontend](https://quickstart-openshift-1611-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1611-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: cleanup deploy

README.md
---
- [Frontend](https://quickstart-openshift-1616-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1616-frontend.apps.silver.devops.gov.bc.ca/api)
=> docs: schedule jobs badge

.github/workflows/merge.yml, .github/workflows/pr-open.yml, .github/workflows/test.yml
---
- [Frontend](https://quickstart-openshift-1621-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1621-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: investigate payloads

.github/workflows/test.yml
---
- [Frontend](https://quickstart-openshift-1622-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1622-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: merge trigger event

.github/workflows/test.yml
---
- [Frontend](https://quickstart-openshift-1624-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1624-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: revise main dump

.github/workflows/.deploy.yml, .github/workflows/merge.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1631-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1631-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: test merge workflow

.github/workflows/pr-open.yml, frontend/Dockerfile
---
- [Frontend](https://quickstart-openshift-1632-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1632-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: test merge

.github/workflows/.deploy.yml, .github/workflows/merge.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml, frontend/Dockerfile
---
- [Frontend](https://quickstart-openshift-1630-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1630-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: simplify workflows

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1634-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1634-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: merge workflow

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1635-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1635-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: keep working on main

.github/workflows/contexts.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1636-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1636-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: troubleshoot with dump github.event

.github/workflows/contexts.yml
---
- [Frontend](https://quickstart-openshift-1638-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1638-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: toJson dump

.github/workflows/contexts.yml
---
- [Frontend](https://quickstart-openshift-1639-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1639-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: dump whole github context

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1642-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1642-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: troubleshooting

.github/workflows/merge.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1643-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1643-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: troubleshooting II

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1644-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1644-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: merge workflow pr var

.github/workflows/merge.yml, .github/workflows/pr-open.yml
After the last whirlwind of changes it looks like there's enough to warrant a cleanup.
---
- [Frontend](https://quickstart-openshift-1645-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1645-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: cleanup

charts/quickstart-openshift/values.yaml, frontend/src/components/Dashboard.tsx
---
- [Frontend](https://quickstart-openshift-1664-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1664-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: values.globals.podAnnotations

.github/workflows/.deploy.yml, .github/workflows/merge.yml, frontend/src/components/Dashboard.tsx
---
- [Frontend](https://quickstart-openshift-1660-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1660-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: helm package before deploy to add proper versioning for the app

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1673-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1673-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: tag w/ PR_no instead of semver (failing)

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1675-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1675-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: push to main not reflected on GH

charts/quickstart-openshift/templates/knp.yaml
---
- [Frontend](https://quickstart-openshift-1676-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1676-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat(helm): changes to knp to add more specific network rules.

charts/quickstart-openshift/values.yaml
---
- [Frontend](https://quickstart-openshift-1678-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1678-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(flyway): Add connection retries.

.github/workflows/merge.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1680-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1680-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: ci/main merge

.github/workflows/merge.yml
=> fix: missing checkout

.github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-1682-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1682-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: ci pr close

.github/workflows/.deploy.yml, .github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1684-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1684-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: use PR_no instead of semver for TEST/PROD release

.github/workflows/merge.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1689-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1689-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: simplify merge queues

.github/workflows/merge.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1691-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1691-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: adjust merge workflow

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1693-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1693-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: fix prod prereq

.github/workflows/pr-open.yml, charts/quickstart-openshift/templates/secret.yaml
---
- [Frontend](https://quickstart-openshift-1685-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1685-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(helm): reuse existing password or generate password during install as default and dont fail pipeline.

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1696-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1696-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): fix hard coded value in merge workflow

.github/codeowners
---
- [Frontend](https://quickstart-openshift-1700-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1700-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: sample .github/codeowners

.github/workflows/analysis.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1704-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1704-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: lighten merge group runs

charts/quickstart-openshift/Chart.yaml, charts/quickstart-openshift/README.md, charts/quickstart-openshift/README.md.gotmpl, charts/quickstart-openshift/values.yaml
---
- [Frontend](https://quickstart-openshift-1699-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1699-frontend.apps.silver.devops.gov.bc.ca/api)
=> docs(helm): add documentation for HELM

.github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1711-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1711-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: revise interrupt conditional

.github/workflows/analysis.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1712-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1712-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: test conditional

.github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1713-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1713-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: avoid collisions with merge group SHAs

.github/workflows/load-test.yml, load-test/README.md, load-test/backend-test.js, load-test/frontend-test.js
Load Testing sample for dev teams.
---
- [Frontend](https://quickstart-openshift-1721-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1721-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: Load TEST

.github/workflows/load-test.yml
1. fix the path
2. parameterize the vu and duration for workflow_dispatch
---
- [Frontend](https://quickstart-openshift-1722-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1722-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: Load TEST

.github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-1743-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1743-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: only let MERGED PRs promote images

README.md
Briefly mention merge queues.  They are not recommended, so very little detail is required.
---
- [Frontend](https://quickstart-openshift-1751-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1751-frontend.apps.silver.devops.gov.bc.ca/api)
=> docs: merge queues

.github/workflows/scheduled.yml, backend/.dockerignore, frontend/.dockerignore
---
- [Frontend](https://quickstart-openshift-1757-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1757-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: helm cleanup overkill

README.md
---
- [Frontend](https://quickstart-openshift-1782-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1782-frontend.apps.silver.devops.gov.bc.ca/api)
=> docs: Added recently added features to the stack.

.github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-1789-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1789-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(CI): remove hardcoded directory

.github/workflows/notifications.yml
Info and an example for Microsoft Teams notifications.
---
- [Frontend](https://quickstart-openshift-1791-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1791-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): manage webhooks example

.github/workflows/.tests.yml, .github/workflows/pr-open.yml
Clean up workflows:
- update builder for node16 deprecation warnings
- fix .tests.yml inputs for that failure
---
- [Frontend](https://quickstart-openshift-1797-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1797-frontend.apps.silver.devops.gov.bc.ca/api)
---
- [Frontend](https://quickstart-openshift-1797-frontend.apps.silver.devop …
=> chore(deps): workflow updates and cleanup

charts/quickstart-openshift/values.yaml
---
- [Frontend](https://quickstart-openshift-1798-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1798-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(helm): pvc block

.github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-1816-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1816-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(deps): set version for pr-close workflow

.github/workflows/analysis.yml, .github/workflows/pr-close.yml, .github/workflows/pr-edit.yml, .github/workflows/pr-open.yml
- use shared code for pr-validate
- add workflow for pr-edit using the same code
---
- [Frontend](https://quickstart-openshift-1817-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1817-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): shared pr-validate and new pr-edit workflows

charts/quickstart-openshift/Chart.lock, charts/quickstart-openshift/templates/backend/templates/_helpers.tpl, charts/quickstart-openshift/templates/backend/templates/deployment.yaml, charts/quickstart-openshift/templates/frontend/templates/_helpers.tpl, charts/quickstart-openshift/templates/frontend/templates/deployment.yaml
---
- [Frontend](https://quickstart-openshift-1821-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1821-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: helm labels

charts/quickstart-openshift/templates/backend/templates/_helpers.tpl, charts/quickstart-openshift/templates/frontend/templates/_helpers.tpl
---
- [Frontend](https://quickstart-openshift-1824-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1824-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: helm labels to support KNPs

.github/workflows/.deploy.yml
---
- [Frontend](https://quickstart-openshift-1825-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1825-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: remove unnecessary deploy params

charts/quickstart-openshift/templates/secret.yaml
---
- [Frontend](https://quickstart-openshift-1826-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1826-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: remove quote from auto generated password

.github/workflows/pr-edit.yml
---
- [Frontend](https://quickstart-openshift-1831-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1831-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(ci): shared workflow version number

LICENSE
---
- [Frontend](https://quickstart-openshift-1843-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1843-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(docs): license copyright

charts/quickstart-openshift/templates/secret.yaml
---
- [Frontend](https://quickstart-openshift-1853-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1853-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): use label so Helm stops replacing secrets

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-1855-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1855-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): remove old params from merge deploys

.github/workflows/merge.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml, .github/workflows/scheduled.yml, README.md
---
- [Frontend](https://quickstart-openshift-1856-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1856-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): make oc_namespace a secret for workflow_call

.github/workflows/merge.yml, .github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-1863-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1863-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): loosen merge prerequisites, job name

.github/workflows/pr-open.yml
Failing PR passed anyway and was merged.  Prevent this from happening again.
https://github.com/bcgov/quickstart-openshift/pull/1887
---
- [Frontend](https://quickstart-openshift-1890-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1890-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(ci): false pass

frontend/Dockerfile, frontend/index.html
---
- [Frontend](https://quickstart-openshift-1900-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1900-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: make sure favicon shows in browser for frontend

charts/app/templates/backend/templates/deployment.yaml
---
- [Frontend](https://quickstart-openshift-1949-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1949-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(ci): backend containers resources

.github/workflows/scheduled.yml
---
- [Frontend](https://quickstart-openshift-1955-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1955-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(CI): point schemaspy to proper schema

backend/package-lock.json, frontend/package-lock.json
Reverts bcgov/quickstart-openshift#1962
---
- [Frontend](https://quickstart-openshift-1963-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-1963-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: evert "chore(deps): lock file maintenance"

docker-compose.yml, frontend/Dockerfile
---
- [Frontend](https://quickstart-openshift-2006-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2006-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(deps): node 22 for frontend

.github/workflows/scheduled.yml
---
- [Frontend](https://quickstart-openshift-2015-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2015-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(ci): run ZAP scans sequentially for rate limiting

frontend/package-lock.json, frontend/package.json
https://github.com/bcgov/quickstart-openshift/security/dependabot/57
---
- [Frontend](https://quickstart-openshift-2017-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2017-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(deps): bump ws for alert

.github/workflows/pr-open.yml, .github/workflows/scheduled.yml
---
- [Frontend](https://quickstart-openshift-2019-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2019-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): ZAP backend path

README.md
---
- [Frontend](https://quickstart-openshift-2036-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2036-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(docs): gold cluster link

backend/Dockerfile
Update Dockerfile ENV formatting.  Recommended by CodeQL.
---
- [Frontend](https://quickstart-openshift-2059-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2059-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): Dockerfile adjustments

.github/workflows/analysis.yml, .github/workflows/pr-open.yml
PR #2071 merged despite a failing job and will be reverted out shortly.  This PR will hopefully prevent that from happening again.
---
- [Frontend](https://quickstart-openshift-2074-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2074-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(ci): merge on failure

backend/src/common/logger.config.ts, backend/src/main.ts
---
- [Frontend](https://quickstart-openshift-2079-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2079-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: log process startup time

backend/src/common/logger.config.ts, backend/src/main.ts
---
- [Frontend](https://quickstart-openshift-2080-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2080-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: log-color

charts/app/templates/secret.yaml
---
- [Frontend](https://quickstart-openshift-2089-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2089-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: secret fetch logic.

README.md
Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.
---
- [Frontend](https://quickstart-openshift-2101-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2101-frontend.apps.silver.devops.gov.bc.ca/api) …
=> fix: added webhook & env setup to readme

renovate.json
---
- [Frontend](https://quickstart-openshift-2103-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2103-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): remove renovate setting, now upstream

.github/workflows/.dbdeployer.yml
---
- [Frontend](https://quickstart-openshift-2137-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2137-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: Crunchy db deployer env check

.github/workflows/.dbdeployer.yml, README.md, docker-compose.yml
---
- [Frontend](https://quickstart-openshift-2139-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2139-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: documentation update, and add a way for teams to provide separate values file for different environments with different resource needs.

.github/workflows/notifications.yml
---
- [Frontend](https://quickstart-openshift-2141-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2141-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: silent unnecessary notification failures for each run

charts/crunchy/templates/PostgresCluster.yaml, charts/crunchy/values.yaml
---
- [Frontend](https://quickstart-openshift-2143-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2143-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: add pg_hba conf

.github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-2149-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2149-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: pr user removal on pr close

charts/crunchy/values.yaml, tests/load/backend-test.js, tests/load/frontend-test.js
---
- [Frontend](https://quickstart-openshift-2151-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2151-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: load test k6

charts/crunchy/values.yaml
---
- [Frontend](https://quickstart-openshift-2160-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2160-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(deps): upgrading to 3.4 of postgis

.github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-2180-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2180-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(ci): update and test for new repo/package builder bug

.github/workflows/analysis.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-2192-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2192-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(ci): gate on canceled jobs

.github/workflows/analysis.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-2193-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2193-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: fix Results checks

.github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-2199-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2199-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: add PR numbers to PR deploys and tests

backend/package-lock.json, backend/package.json
https://github.com/bcgov/quickstart-openshift/security/dependabot/80
---
- [Frontend](https://quickstart-openshift-2201-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2201-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(deps): alert

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-2207-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2207-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: fix merge tags

.github/workflows/merge.yml
---
- [Frontend](https://quickstart-openshift-2208-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2208-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: fix merge tags (again)

.github/workflows/.deployer-db.yml, .github/workflows/.deployer.yml, .github/workflows/merge.yml
Simplify merge tag to make @mishraomp  happy.  (and myself by fixing a missing needs param)
---
- [Frontend](https://quickstart-openshift-2209-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2209-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: simplify merge tag

charts/app/templates/backend/templates/deployment.yaml, migrations/Dockerfile
---
- [Frontend](https://quickstart-openshift-2211-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2211-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: flyway

README.md
---
- [Frontend](https://quickstart-openshift-2214-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2214-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(docs): Add documentation around flyway, prisma, migrations

.github/workflows/scheduled.yml
Conditional error.  Whoops.
---
- [Frontend](https://quickstart-openshift-2227-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2227-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(ci): conditional

backend/src/prisma.service.ts, charts/crunchy/templates/PostgresCluster.yaml, charts/crunchy/values.yaml
---
- [Frontend](https://quickstart-openshift-2231-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2231-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: remove images entirely from charts

.github/workflows/.deployer.yml
---
- [Frontend](https://quickstart-openshift-2237-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2237-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(ci): get promote tag from deployer

.github/workflows/.deployer.yml, .github/workflows/analysis.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-2245-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2245-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): update action org, now bcgov

.github/workflows/analysis.yml
---
- [Frontend](https://quickstart-openshift-2258-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2258-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix(ci): trivy permissions

.github/workflows/.deployer-db.yml, .github/workflows/.tests.yml, .github/workflows/analysis.yml, .github/workflows/demo.yml, .github/workflows/notifications.yml
---
- [Frontend](https://quickstart-openshift-2259-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2259-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): remove JS blocks in workflow conditionals

.github/workflows/analysis.yml
---
- [Frontend](https://quickstart-openshift-2266-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2266-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): allow Trivy to fail

frontend/Caddyfile
---
- [Frontend](https://quickstart-openshift-2267-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2267-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: caddy improvements

frontend/Caddyfile
---
- [Frontend](https://quickstart-openshift-2269-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2269-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: caddy warning around metrics

frontend/Caddyfile
---
- [Frontend](https://quickstart-openshift-2270-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2270-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: caddy warnings

.github/workflows/analysis.yml, .github/workflows/pr-open.yml
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/278
---
- [Frontend](https://quickstart-openshift-2281-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2281-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): handle secrets conditionally to avoid over exposure

.github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-2284-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2284-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): uncomment triggers during cleanup

.github/workflows/.deployer-db.yml, .github/workflows/.deployer.yml, .github/workflows/analysis.yml, .github/workflows/demo.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml, .github/workflows/scheduled.yml
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/285
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/293
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/304
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/305
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/306
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/307
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/308
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/309
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/310
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/312
- …
=> chore(ci): pin bcgov actions

.github/workflows/.tests.yml, .github/workflows/analysis.yml, .github/workflows/merge.yml, .github/workflows/notifications.yml, .github/workflows/scheduled.yml
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/280
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/281
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/283
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/288
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/290
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/291
- https://github.com/bcgov/quickstart-openshift/security/code-scanning/295
---
- [Frontend](https://quickstart-openshift-2288-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2288-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in …
=> chore(ci): pin non-bcgov actions

.github/workflows/notifications.yml
Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.
---
- [Frontend](https://quickstart-openshift-2302-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2302-frontend.apps.silver.devops.gov.bc.ca/api) …
=> fix: removed the '!=' comparison from the webhook url in merged.

.github/workflows/.deployer.yml
---
- [Frontend](https://quickstart-openshift-2348-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2348-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): disable atomic deployments

.github/workflows/notifications.yml, README.md
I took @MonicaG's advice and let Copilot take a swing at this readme!  Also includes additional human-led changes.  ;)
---
- [Frontend](https://quickstart-openshift-2350-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2350-frontend.apps.silver.devops.gov.bc.ca/api)
=> docs: readme

README.md
---
- [Frontend](https://quickstart-openshift-2354-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2354-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: colorful mermaid

.github/workflows/pr-close.yml, .github/workflows/pr-validate.yml, .github/workflows/scheduled.yml
---
- [Frontend](https://quickstart-openshift-2357-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2357-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): revert merged actions prerelease

.github/workflows/.deployer.yml, .github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-2359-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2359-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: update to action crunchy 1.0.1

charts/crunchy/values.yml
---
- [Frontend](https://quickstart-openshift-2360-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2360-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: align to min resources

.github/workflows/.deployer.yml, .github/workflows/pr-close.yml
---
- [Frontend](https://quickstart-openshift-2361-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2361-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: upgrade crunchy action

README.md
---
- [Frontend](https://quickstart-openshift-2362-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2362-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(docs): crunchy reusable GHA docs

README.md
---
- [Frontend](https://quickstart-openshift-2363-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2363-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: typo and ref to links

.github/workflows/.deployer.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-2382-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2382-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore:  update crunchy action

.github/workflows/pr-open.yml
---
- [Frontend](https://quickstart-openshift-2387-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2387-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): update builder action

backend/Dockerfile, docker-compose.yml, frontend/Dockerfile, migrations/Dockerfile
Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.
---
- [Frontend](https://quickstart-openshift-2394-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2394-frontend.apps.silver.devops.gov.bc.ca/api) …
=> chore(ci): drop Docker digests

HOWTO.md, README.md
---
- [Frontend](https://quickstart-openshift-2405-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2405-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: first howto, many more to come

.github/workflows/analysis.yml
---
- [Frontend](https://quickstart-openshift-2411-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2411-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): stop pinning containers in actions workflows

.github/pull_request_template.md
Improved PR template courtesy of @paulushcgcj.  :smile:
---
- [Frontend](https://quickstart-openshift-2480-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2480-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): use pr template from @paulushcgcj

charts/app/templates/backend/templates/deployment.yaml, charts/app/templates/frontend/templates/deployment.yaml
---
- [Frontend](https://quickstart-openshift-2483-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-2483-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: add startup probes
